### ISSUE TITLE
[BITS] interpret decimal as binary

### ISSUE THREAD

**Issue by derpicknicker1** [j-zero/ConsoleUtils#4]
## What happens
`11111111` as parameter was interpreted as binary number.

## What is expected
As the parameter `11111111` is not explicitly marked as binary, it should be interpreted as decimal number.

![image](https://github.com/j-zero/ConsoleUtils/assets/5983533/e47a1f2a-b19e-49ae-b0cb-721315999e2c)

**Comment by j-zero** [comment]
fixed.
